### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by itsj4y** [dipen30/Qmote#1]
Can you update this to swift 3.0 please?

**Comment by jaysavsani1** [comment]
Hey, 
We're currently working on it and almost half of the code is already converted to swift 3.0
We'll be done in couple of weeks.

**Comment by itsj4y** [comment]
Ok cool I tried to update it using the built in update function in Xcode but it gives a lot of errors.

**Comment by jaysavsani1** [comment]
Hey
I'm currently working on it and already solved most of the errors. I've also added some cool new features as well. Will be done by this weekend.

**Comment by dipen30** [comment]
Closing this against pull request

https://github.com/dipen30/Qmote/pull/2
